name: Release ARMv7 wheel

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout PyTorch source
        run: |
          rm -rf pytorch
          git clone --recursive https://github.com/pytorch/pytorch.git pytorch
          cd pytorch
          git fetch --all --tags
          echo "Checking out PyTorch version: ${{ github.ref_name }}"
          git checkout ${{ github.ref_name }} || { echo "Tag not found!"; exit 1; }
          git submodule update --init --recursive

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build wheel
        run: |
          DOCKER_BUILDKIT=1 docker build \
            --platform linux/arm/v7 \
            --build-arg MAX_JOBS=32 \
            --build-arg PYTHON_VERSION=${{ matrix.python-version }} \
            --target wheel-export \
            --output type=local,dest=./dist \
            .

      - name: Create release and upload wheel
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: dist/*.whl
